const agents = [
    "Astra", "Breach", "Brimstone", "Chamber", "Cypher", "Fade", "Gekko",
    "Harbor", "Jett", "KAY/O", "Killjoy", "Neon", "Omen", "Phoenix",
    "Raze", "Reyna", "Sage", "Skye", "Sova", "Viper", "Yoru"
];

const positiveQuotes = [
    "Believe you can and you're halfway there.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only way to do great work is to love what you do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Good things come to those who hustle.",
    "Success is not for the lazy.",
    "The secret of getting ahead is getting started.",
    "It's not about perfect. It's about effort.",
    "It always seems impossible until it's done.",
    "Don't watch the clock; do what it does. Keep going.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The future depends on what you do today.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Act as if what you do makes a difference. It does.",
    "With the new day comes new strength and new thoughts.",
    "Quality is not an act, it is a habit.",
    "Failure will never overtake me if my determination to succeed is strong enough.",
    "The only place where success comes before work is in the dictionary.",
    "Don't wait for the perfect moment, take the moment and make it perfect.",
    "The only way to achieve the impossible is to believe it is possible.",
    "You are capable of amazing things.",
    "Focus on the journey, not the destination.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The only person you are destined to become is the person you decide to be.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Start where you are. Use what you have. Do what you can.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your present circumstances don't determine where you can go; they merely determine where you start.",
    "The only way to do great work is to love what you do.",
    "Don't be afraid to give up the good to go for the great.",
    "A positive mindset brings positive things.",
    "Positivity always wins…Always."
];

module.exports = {
    agents,
    positiveQuotes
  };